version: "3.9"
services:
  server:
    container_name: server
    build: ./server
    command: yarn start:dev
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
  client:
    container_name: client
    build: ./client
    command: yarn start:dev
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
